{
  "formatVersion": "1.1",
  "component": {
    "group": "com.smg",
    "module": "smg-surveysdk",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "smg-surveysdk-0.5.2.aar",
          "url": "smg-surveysdk-0.5.2.aar",
          "size": 357564,
          "sha512": "62219cb7456b88b013c0c2fb29a8a68c29c8333adbf7490a849b369faf572eefaf1618fb0ae88ebcaa23baf4bb068906555e04d4c58e1b37f088c6fa8b5567d1",
          "sha256": "16e24c25552b9bc70cd002f62c22023b20d9b947f1e4fd7e8ec422429f2a9ce3",
          "sha1": "a1aea02ed2081099d8e7381c865e2905fa997d4e",
          "md5": "7d8b1743e5c7eecd7d62eb9446041793"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "smg-surveysdk-0.5.2.aar",
          "url": "smg-surveysdk-0.5.2.aar",
          "size": 357564,
          "sha512": "62219cb7456b88b013c0c2fb29a8a68c29c8333adbf7490a849b369faf572eefaf1618fb0ae88ebcaa23baf4bb068906555e04d4c58e1b37f088c6fa8b5567d1",
          "sha256": "16e24c25552b9bc70cd002f62c22023b20d9b947f1e4fd7e8ec422429f2a9ce3",
          "sha1": "a1aea02ed2081099d8e7381c865e2905fa997d4e",
          "md5": "7d8b1743e5c7eecd7d62eb9446041793"
        }
      ]
    }
  ]
}
