{
  "formatVersion": "1.1",
  "component": {
    "group": "com.smg",
    "module": "smg-surveysdk",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "smg-surveysdk-0.5.3.aar",
          "url": "smg-surveysdk-0.5.3.aar",
          "size": 361017,
          "sha512": "8321f309c1db3a41836165e8ee573672a34d2db0c1aee47c017d5a63a87bff3f73e1e24a6253c009199fec9616fd67fb9b301114d5107a806c3abdc6d7142aa9",
          "sha256": "0a2ee8dc89a4b6740885d11c1088bcf93c5826e7f5bdb550dc527f68d4204abb",
          "sha1": "dccdcc9d341f64b159f45469f71be26f621028dd",
          "md5": "807d058ca0dfc028100e6ae9ea7ce58b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "smg-surveysdk-0.5.3.aar",
          "url": "smg-surveysdk-0.5.3.aar",
          "size": 361017,
          "sha512": "8321f309c1db3a41836165e8ee573672a34d2db0c1aee47c017d5a63a87bff3f73e1e24a6253c009199fec9616fd67fb9b301114d5107a806c3abdc6d7142aa9",
          "sha256": "0a2ee8dc89a4b6740885d11c1088bcf93c5826e7f5bdb550dc527f68d4204abb",
          "sha1": "dccdcc9d341f64b159f45469f71be26f621028dd",
          "md5": "807d058ca0dfc028100e6ae9ea7ce58b"
        }
      ]
    }
  ]
}
